# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SessionStats.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SessionDurationLabel = QtWidgets.QLabel(self.centralwidget)
        self.SessionDurationLabel.setGeometry(QtCore.QRect(40, 50, 500, 61))
        self.SessionDurationLabel.setObjectName("SessionDurationLabel")
        self.YourTimeRelaxedLabel = QtWidgets.QLabel(self.centralwidget)
        self.YourTimeRelaxedLabel.setGeometry(QtCore.QRect(40, 100, 500, 61))
        self.YourTimeRelaxedLabel.setObjectName("YourTimeRelaxedLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 500, 61))
        self.label_3.setObjectName("StimulatingAudioLabel")
        self.YourTimeRelaxedLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.YourTimeRelaxedLabel_2.setGeometry(QtCore.QRect(40, 150, 261, 61))
        self.YourTimeRelaxedLabel_2.setObjectName("Avera")
        self.ExitStatsButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitStatsButton.setGeometry(QtCore.QRect(10, 640, 500, 91))
        self.ExitStatsButton.setStyleSheet("background-color: rgb(237, 51, 59);\n"
"border-radius: 30px;")
        self.ExitStatsButton.setObjectName("ExitStatsButton")
        self.ExitStatsButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ExitStatsButton_2.setGeometry(QtCore.QRect(160, 640, 111, 91))
        self.ExitStatsButton_2.setStyleSheet("background-color: rgb(143, 240, 164);\n"
"border-radius: 30px;")
        self.ExitStatsButton_2.setObjectName("ExitStatsButton_2")
        self.RelaxationVsTime = QtWidgets.QFrame(self.centralwidget)
        self.RelaxationVsTime.setGeometry(QtCore.QRect(40, 280, 341, 301))
        self.RelaxationVsTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RelaxationVsTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RelaxationVsTime.setObjectName("RelaxationVsTime")
        self.AudioVsTime = QtWidgets.QFrame(self.centralwidget)
        self.AudioVsTime.setGeometry(QtCore.QRect(480, 280, 341, 301))
        self.AudioVsTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AudioVsTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AudioVsTime.setObjectName("AudioVsTime")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SessionDurationLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Session Duration:</span></p></body></html>"))
        self.YourTimeRelaxedLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Your Time Relaxed:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Most &quot;Engaging&quot; Audio:</span></p></body></html>"))
        self.YourTimeRelaxedLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Average Relaxation Score:</span></p></body></html>"))
        self.ExitStatsButton.setText(_translate("MainWindow", "CLOSE"))
        self.ExitStatsButton_2.setText(_translate("MainWindow", "REDO SESSION"))

